# GitHub Pages configuration for netcdf4-wasm documentation

# Site settings
title: netcdf4-wasm
description: NetCDF4 library compiled to WebAssembly with JavaScript/TypeScript bindings
baseurl: "" # Set by GitHub Actions automatically
url: "" # Set by GitHub Actions automatically

# GitHub Pages settings
repository: oceanum-io/netcdf4-wasm
github:
  owner_name: oceanum-io
  repository_name: netcdf4-wasm

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Navigation
header_pages:
  - guides/index.md
  - api/index.md
  - examples/index.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from build
exclude:
  - node_modules/
  - package*.json
  - tsconfig.json
  - jest.config.js
  - scripts/
  - src/
  - build/
  - dist/
  - .gitignore
  - README.md

# Kramdown settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Collections
collections:
  guides:
    output: true
    permalink: /guides/:name/
  examples:
    output: true
    permalink: /examples/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_guides"
      type: "guides"
    values:
      layout: "page"
  - scope:
      path: "_examples"
      type: "examples"
    values:
      layout: "page"